### ISSUE TITLE
App.UI cant be deployed

### ISSUE THREAD

**Issue by MrCirca** [Azure/Mission-Critical-Connected#438]
Hi,
I am trying to run Mission-Critical pipeline and App.UI cant be deployed. 

`
; node bin location = /usr/local/bin/node
; node version = v16.19.0
; npm local prefix = /home/vsts/work/1/s/src/app/AlwaysOn.UI
; npm version = 8.19.3
; cwd = /home/vsts/work/1/s/src/app/AlwaysOn.UI
; HOME = /home/vsts
; Run `npm config ls -l` to show all defaults.
/usr/local/bin/npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility

npm ERR! code ENOENT
> html-ui@0.1.0 preinstall
npm ERR! syscall lstat
> npx npm-force-resolutions
npm ERR! path /home/vsts/work/1/s/src/app/AlwaysOn.UI/at5e2e

npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/home/vsts/work/1/s/src/app/AlwaysOn.UI/at5e2e'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vsts/.npm/_logs/2023-02-07T14_29_03_630Z-debug-0.log
npm ERR! code 254
npm ERR! path /home/vsts/work/1/s/src/app/AlwaysOn.UI
npm ERR! command failed
npm ERR! command sh -c -- npx npm-force-resolutions

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vsts/.npm/_logs/2023-02-07T14_28_55_933Z-debug-0.log
`

**Comment by sebader** [comment]
sorry for the late reply! tagging @msimecek for UI related topics

**Comment by msimecek** [comment]
@MrCirca Which step is failing for you? Looks like "NPM install", but double-checking.

Are you using the latest code from this repo?

Have you done modifications to the pipelines? For instance, our Connected pipeline is setting Node to v18, but in your output I see `node version = v16.19.0` and `npm version = 8.19.3`. The output should be something like this:

```
; node bin location = /agent/_work/_tool/node/18.15.0/x64/bin/node
; node version = v18.15.0
; npm local prefix = /agent/_work/1/s/src/app/AlwaysOn.UI
; npm version = 9.5.0
; cwd = /agent/_work/1/s/src/app/AlwaysOn.UI
; HOME = /home/AzDevOps
```

Also, this path `/home/vsts/work/1/s/src/app/AlwaysOn.UI/at5e2e` is not right, as the prefix shouldn't be added to the end.

**Comment by msimecek** [comment]
Closing for lack of response.
