### ISSUE TITLE
Getting an error with regards to frontdoor.tf file while trying to deploy the 2nd stamp in an existing environment.

### ISSUE THREAD

**Issue by NagaSwamy473** [Azure/Mission-Critical-Connected#517]
Hi All,

I am trying to deploy the 2nd stamp environment within the existing environment(where global resources are already running with 1st stamp. I am getting an error as shown below:
Error: Duplicate object key
│ 
│   on frontdoor.tf line 166, in resource "azurerm_cdn_frontdoor_origin" "backendapi":
│  166:   for_each = { for index, backend in var.backends_BackendApis : backend.address => backend }
│     ├────────────────
│     │ backend.address is "10.0.236.154"
│ 
│ Two different items produced the key "10.0.236.154" in this 'for'
│ expression. If duplicates are expected, use the ellipsis (...) after the
│ value expression to enable grouping by key.
╵
##[error]Bash exited with code '1'.

Looking forward to get the help in fixing the issues.
![image](https://user-images.githubusercontent.com/131235082/233001060-67f54c5b-f2a7-4c65-940a-f5fe39b1c425.png)

**Comment by sebader** [comment]
discussed offline
