### ISSUE TITLE
Getting an error related to location required to create/deploy the storage account.

### ISSUE THREAD

**Issue by NagaSwamy473** [Azure/Mission-Critical-Connected#518]
Hi All,
I am trying to deploy entire new environment with 2 stamps by selecting the locations from the list which you have been provided but getting an error related to location required to create/deploy the storage account.

*** Creating Private Endpoints for terraform state storage costintterraformstate 
ERROR: (LocationRequired) The location property is required for this definition. 
Code: LocationRequired 
Message: The location property is required for this definition. 
*** Error - could not create storage private endpoint 
At /agent/_work/_temp/azureclitaskscript1681888817205_inlinescript.ps1:56 char:5 
+ throw "*** Error - could not create storage private endpoint" 
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
+ CategoryInfo : OperationStopped: (*** Error - could n…ge private endpoint:String) [], RuntimeException 
+ FullyQualifiedErrorId : *** Error - could not create storage private endpoint 
##[error]Script failed with exit code: 1 
Can someone help me to fix this issue.

**Comment by sebader** [comment]
Are you using the latest version from this repo? There was a bug which was fix mid-March.

**Comment by NagaSwamy473** [comment]
Hi Sebastin,
No, we are using the repos which was cloned in the month of December and added few more terraform components to deploy the extra resources which we require to host our platform.
Could you please help me with the fix which has been done by MS in the month of march. Is it something which is related to frontdoor in specific?

**Comment by sebader** [comment]
specifically it was this change: https://github.com/Azure/Mission-Critical-Connected/pull/472/files#diff-b7779917038f3bf5e134ea095755151378b44c33deab900de2b14441b98c37c9

But in general you should look into porting changes that were made here since then into your repo, too.

**Comment by sebader** [comment]
closed as discussed offline. The latest version in this repo fixes the issue
