### ISSUE TITLE
Replace Azure Front Door with Traffic Manager

### ISSUE THREAD

**Issue by DavidDury** [Azure/Mission-Critical-Connected#551]
In this configuration will it be possible to replace front door with traffic manager instead?

**Comment by sebader** [comment]
In theory, yes. However, this version uses private ingress points for each of the backend clusters. Traffic Manager requires public endpoints. On the [-Online reference implementation](https://github.com/Azure/Mission-Critical-Online) those endpoints are exposed on Public IPs, which would make that switch a bit easier. But it will still require bigger rework effort.
What's your reason to change, if I may ask?

**Comment by DavidDury** [comment]
Yeah that's the beauty of the Front-Door all traffic goes through it compared to Traffic Manager. The reason why I need Traffic Manager is because I need to support Layer 4 TCP connectivity

**Comment by DavidDury** [comment]
Thanks, appreciated :)
