### ISSUE TITLE
Why not use bicep?

### ISSUE THREAD

**Issue by dazinator** [Azure/Mission-Critical-Connected#586]
Any plans to use Bicep instead of Terraform? It seems odd to not champion your own infra deployment tech stack..

**Comment by dazinator** [comment]
It seems you do use bicep, but terraform is mentioned in places too which confused me!

**Comment by sebader** [comment]
Bicep is used for the infrastructure of the build agent - and supporting infra like the Terraform state storage. The main deployment happens with Terraform.

**Comment by dazinator** [comment]
I see. Is there a reason why bicep isn't used for all resource deployments given this is entirely scoped to azure resources and bicep is meant to enable a first party experience? Is it because terraform is more widely adopted for example? If so why the mix and match between the two technologies?
