### ISSUE TITLE
Ubuntu kubernetes-xenial package repository issue

### ISSUE THREAD

**Issue by cbezenco** [Azure/Mission-Critical-Connected#825]
Getting this error when trying to deploy the solultion. 
Seems Xenial / 1.22 has been removed 2 days ago. Pipelines needs to be updated.
https://github.com/kubernetes/release/issues/3485

========================== Starting Command Output ===========================
/usr/bin/bash /agent/_work/_temp/cc130d3f-61b9-47f6-9c52-f9e4672c9168.sh
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 https://packages.microsoft.com/repos/azure-cli focal InRelease
Hit:3 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:7 https://apt.releases.hashicorp.com/ focal InRelease
Ign:8 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Err:9 https://packages.cloud.google.com/apt kubernetes-xenial Release
  404  Not Found [IP: 74.125.193.101 443]
Reading package lists...
E: The repository 'https://packages.cloud.google.com/apt kubernetes-xenial Release' does not have a Release file.
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 https://packages.microsoft.com/repos/azure-cli focal InRelease
Hit:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Ign:6 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
Hit:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Err:8 https://packages.cloud.google.com/apt kubernetes-xenial Release
  404  Not Found [IP: 74.125.193.101 443]
Hit:9 https://apt.releases.hashicorp.com/ focal InRelease
Reading package lists...
E: The repository 'https://packages.cloud.google.com/apt kubernetes-xenial Release' does not have a Release file.

##[error]Bash exited with code '100'.
Finishing: Install Terraform CLI v1.6.2-*

**Comment by sebader** [comment]
Ok, I merged the fixed version to main. You'll need to update your build agents by running the build-agent pipeline once again based on the latest version 

https://github.com/Azure/Mission-Critical-Connected/blob/main/docs/reference-implementation/Private-Agents-Setup.md#deploy-self-hosted-build-agent-infrastructure
